apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
